### ISSUE TITLE
Move to travis.com

### ISSUE THREAD

**Issue by mauro3** [nignatiadis/SmoothingSplines.jl#21]
https://discourse.julialang.org/t/reminder-travis-ci-org-shuts-down-on-december-31-2020/47234/12

**Comment by nignatiadis** [comment]
What do you think about just replacing everything (travis and appveyor) by Github Actions?

**Comment by mauro3** [comment]
That would be fine too.  Although, I don't know the scripts for this.  Presumably PkgTemplates can do it?

**Comment by nignatiadis** [comment]
Yeah I think so, I will try to do it later today!
